# Generated by Django 5.0.6 on 2024-10-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smileapp", "0002_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="products/%Y/%m/%d"),
        ),
    ]
