# Generated by Django 5.0.6 on 2024-10-19 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smileapp", "0004_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
