# Generated by Django 5.0.6 on 2024-10-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smileapp", "0008_contactmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart_items",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(default="Unknown", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="cash", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
