# Generated by Django 5.0.6 on 2024-10-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smileapp", "0009_remove_order_cart_items_order_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="created_at",
            new_name="order_date",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="address",
            new_name="shipping_address",
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(default="unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="zip_code",
            field=models.CharField(default="000000", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="Pending", max_length=20),
        ),
    ]
